(ns oracle.state)

(defonce error (atom nil))
(defonce app {:scene (atom "main-menu")
              :ui-mode (atom :none)
              :user-fbid (atom nil)
              :user-hash (atom nil)
              :user-id (atom nil)
              :user-name (atom nil)
              :friend-fbids (atom [])
              :friend-hashes (atom [])
              :friends2 (atom [])
              :exchange-rates (atom {})
              :seconds-since-last-exchange-rates-refresh (atom {})
              :seconds-until-next-reconnect (atom nil)
              :sell-offer (atom nil)
              :sell-offer-matches (atom [])
              :buy-requests (atom [])
              :contracts (atom nil)
              :notifications (atom cljs.core/PersistentQueue.EMPTY)
              :display-contract (atom nil)
              :server-time (atom nil)})
